### ISSUE TITLE
License Choice

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/simpute-r#27]
We are using MIT License.

Other common license choices include Apache and GNU GPL.

Compared to the other 2 choices, MIT license provides the most freedom and flexibility. Both Apache and GNU GPL are conditional to "state changes", meaning that if users make any modification to the licensed software they must document the changes. Whereas MIT license doesn't have that kind of restrictions. Since our target users are python/R beginners, we honestly don't think they have great documentation habits and we don't want to give them extea work burden to do.

MIT license also doesn't have restrictions on commercial use of our package, which is desired. And just like the other 2, MIT license also requires copyright notice and limitations on liability and warrenty. Of course we want our users to give us a little "citation" or credits when they use our product for free.

Thus we decided to use MIT License.

**Comment by renee-kwon** [comment]
Hi Ken, thanks for posting your reasoning on our license choice. I agree we should keep our package simple for our targeted users.

**Comment by LisaSeq** [comment]
Agreed with the reasoning, I think it is best to keep it simple, as this is aligned with the core principal of our package.

**Comment by Althrun-sun** [comment]
I agree with that.Thank you for your contribution!
