### ISSUE TITLE
January 21 Meeting Minutes

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/simpute-r#6]
For our first milestone for R,

- [x] we will create our own branches and update roxygen comments for our assigned functions
- [ ] check we have everything done for milestone 2
- [ ] read through readme for typos
- [ ] and ken will submit the milestone for the team

Thank you,

**Comment by LisaSeq** [comment]
Completed the branch and update to the roxygen comments for bool_imputer.

**Comment by renee-kwon** [comment]
docstring completed and pull request created for cat_imputer
